--texts_scatter_titles.
DROP TABLE IF EXISTS tea.texts_scatter_titles;

CREATE TABLE tea.texts_scatter_titles (
  code SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  ,chart_title_lv TEXT NOT NULL
  ,chart_title_en TEXT NOT NULL
  ,x_axis_code TEXT NOT NULL
  ,y_axis_code TEXT NOT NULL
  );

ALTER TABLE tea.texts_scatter_titles OWNER TO tea_dev;

GRANT SELECT
  ON TABLE tea.texts_scatter_titles
  TO vdvv_web
    ,editor_texts
    ,admin_texts;

GRANT UPDATE
  ON TABLE tea.texts_scatter_titles
  TO editor_texts
    ,admin_texts;

GRANT DELETE
  ,INSERT
  ON TABLE tea.texts_scatter_titles
  TO admin_texts;

INSERT INTO tea.texts_scatter_titles (
  chart_title_lv
  ,chart_title_en
  ,x_axis_code
  ,y_axis_code
  )
VALUES (
  'Nodarbināto skaits un pievienotā vērtība uz vienu nodarbināto'
  ,'Number of employed and value added per one employed'
  ,'va_emp'
  ,'empl'
  );

INSERT INTO tea.texts_scatter_titles (
  chart_title_lv
  ,chart_title_en
  ,x_axis_code
  ,y_axis_code
  )
VALUES (
  'Nodarbinātības līmenis un pievienotā vērtība uz vienu nodarbināto'
  ,'Employment rate and value added per one employed'
  ,'va_emp'
  ,'empl_level'
  );

INSERT INTO tea.texts_scatter_titles (
  chart_title_lv
  ,chart_title_en
  ,x_axis_code
  ,y_axis_code
  )
VALUES (
  'Darbvietu skaits un pievienotā vērtība'
  ,'Number of jobs and value added'
  ,'va_w'
  ,'wp'
  );

INSERT INTO tea.texts_scatter_titles (
  chart_title_lv
  ,chart_title_en
  ,x_axis_code
  ,y_axis_code
  )
VALUES (
  'Nodarbināto skaits un pievienotā vērtība'
  ,'Number of employed and value added'
  ,'va_h'
  ,'empl'
  );

INSERT INTO tea.texts_scatter_titles (
  chart_title_lv
  ,chart_title_en
  ,x_axis_code
  ,y_axis_code
  )
VALUES (
  'Nodarbinātības līmenis un pievienotā vērtība'
  ,'Employment rate and value added'
  ,'va_h'
  ,'empl_level'
  );

INSERT INTO tea.texts_scatter_titles (
  chart_title_lv
  ,chart_title_en
  ,x_axis_code
  ,y_axis_code
  )
VALUES (
  'Darbvietu skaits uz 100 darbspējas vecuma iedzīvotājiem un pievienotā vērtība uz vienu darbvietu'
  ,'Number of jobs per 100 inhabitants of working age and value added per job'
  ,'va_wp'
  ,'empl_wp_100'
  );

INSERT INTO tea.texts_scatter_titles (
  chart_title_lv
  ,chart_title_en
  ,x_axis_code
  ,y_axis_code
  )
VALUES (
  'Darbvietu skaits uz 100 darbspējas vecuma iedzīvotājiem un pievienotā vērtība'
  ,'Number of jobs per 100 inhabitants of working age and value added'
  ,'va_w'
  ,'empl_wp_100'
  );

INSERT INTO tea.texts_scatter_titles (
  chart_title_lv
  ,chart_title_en
  ,x_axis_code
  ,y_axis_code
  )
VALUES (
  'Darbvietu skaits un pievienotā vērtība uz vienu darbvietu'
  ,'Number of jobs and value added per job'
  ,'va_wp'
  ,'wp'
  );

--texts_scatter_axis_menu.
DROP TABLE IF EXISTS tea.texts_scatter_axis_menu;

CREATE TABLE tea.texts_scatter_axis_menu (
  scatter_axis TEXT NOT NULL
  ,scatter_axis_code TEXT NOT NULL
  ,scatter_axis_menu_lv TEXT NOT NULL
  ,scatter_axis_menu_en TEXT NOT NULL
  ,scatter_axis_display TEXT NOT NULL
  ,scatter_axis_sql TEXT NOT NULL
  ,scatter_axis_comments TEXT
  ,scatter_axis_title_lv TEXT NOT NULL
  ,scatter_axis_title_en TEXT NOT NULL
  ,CONSTRAINT texts_scatter_axis_menu_pkey PRIMARY KEY (
    scatter_axis
    ,scatter_axis_code
    )
  );

ALTER TABLE tea.texts_scatter_axis_menu OWNER TO tea_dev;

GRANT SELECT
  ON TABLE tea.texts_scatter_axis_menu
  TO vdvv_web
    ,editor_texts
    ,admin_texts;

GRANT UPDATE
  ON TABLE tea.texts_scatter_axis_menu
  TO editor_texts
    ,admin_texts;

GRANT DELETE
  ,INSERT
  ON TABLE tea.texts_scatter_axis_menu
  TO admin_texts;
INSERT INTO tea.texts_scatter_axis_menu
VALUES (
  'y'
  ,'empl'
  ,'Nodarbināto skaits'
  ,'Number of employed'
  ,'h'
  ,'SELECT year
  ,level_h "level"
  ,code_h code
  ,value_code vrbl
  ,value_ind
FROM tea.data
WHERE year = $1
  AND level_h = $2
  AND code_w = ''total''
  AND brdwn = $6
  AND brdwn_code = $7
  AND value_code = ''empl'''
  ,NULL
  ,'Nodarbināto skaits'
  ,'Number of employed'
  );

INSERT INTO tea.texts_scatter_axis_menu
VALUES (
  'y'
  ,'empl_level'
  ,'Nodarbinātības līmenis'
  ,'Employment rate'
  ,'h'
  ,'SELECT a.year
  ,a.level_h "level"
  ,a.code_h code
  ,a.value_code vrbl
  ,ROUND(a.value_ind / b.value_ind * 100, 0) value_ind
FROM tea.data a
LEFT JOIN tea.data b ON a.year = b.year
  AND a.level_w = b.level_w
  AND a.level_h = b.level_h
  AND a.code_h = b.code_h
  AND a.code_w = b.code_w
WHERE a.year = $1
  AND a.level_h = $2
  AND a.code_w = ''total''
  AND a.brdwn = $6
  AND a.brdwn_code = $7
  AND a.value_code = ''empl''
  AND b.value_code = ''persons''
  AND b.brdwn = ''pop''
  AND b.brdwn_code = ''y15y64''
  AND b.value_ind > 2'
  ,NULL
  ,'Nodarbinātības līmenis, %'
  ,'Employment rate, %'
  );

INSERT INTO tea.texts_scatter_axis_menu
VALUES (
  'y'
  ,'empl_wp_100'
  ,'Darbvietu skaits uz 100 darbspējas vecuma iedzīvotājiem'
  ,'Number of jobs per 100 inhabitants of working age'
  ,'w'
  ,'SELECT a.year
  ,a.level_h "level"
  ,a.code_h code
  ,a.value_code vrbl
  ,ROUND(b.value_ind / a.value_ind * 100, 2) value_ind
FROM tea.data a
JOIN tea.data b ON a.year = b.year
  AND a.code_h = b.code_w
  AND a.level_h = b.level_w
  AND a.year = b.year
WHERE a.year = $1
  AND a.level_h = $4
  AND a.value_code = ''persons''
  AND a.brdwn = ''pop''
  AND a.brdwn_code = ''y15y64''
  AND b.value_code = ''empl_w''
  AND b.code_h = ''total''
  AND b.brdwn = $6
  AND b.brdwn_code = $7
  AND a.value_ind > 0'
  ,NULL
  ,'Darbvietu skaits uz 100 darbspējas vecuma iedzīvotājiem'
  ,'Number of jobs per 100 inhabitants of working age'
  );

INSERT INTO tea.texts_scatter_axis_menu
VALUES (
  'y'
  ,'wp'
  ,'Darbvietu skaits'
  ,'Number of jobs'
  ,'w'
  ,'SELECT year
  ,level_w "level"
  ,code_w code
  ,value_code vrbl
  ,value_ind
FROM tea.data
WHERE year = $1
  AND level_w = $4
  AND code_h = ''total''
  AND brdwn = $6
  AND brdwn_code = $7
  AND value_code = ''empl_w'''
  ,NULL
  ,'Darbvietu skaits'
  ,'Number of jobs'
  );

INSERT INTO tea.texts_scatter_axis_menu
VALUES (
  'x'
  ,'va_h'
  ,'Pievienotā vērtība'
  ,'Value added'
  ,'h'
  ,'SELECT year
  ,level_h "level"
  ,code_h code
  ,value_code vrbl
  ,value_ind
FROM tea.data
WHERE year = $1
  AND level_h = $2
  AND code_w = ''total''
  AND brdwn = ''total''
  AND brdwn_code = ''total''
  AND value_code = ''value_added''
  AND code_h != ''UNK'''
  ,NULL
  ,'Pievienotā vērtība, €'
  ,'Value added, €'
  );

INSERT INTO tea.texts_scatter_axis_menu
VALUES (
  'x'
  ,'va_wp'
  ,'Pievienotā vērtība uz vienu darbvietu'
  ,'Value added per job'
  ,'w'
  ,'SELECT a.year
  ,a.level_w "level"
  ,a.code_w code
  ,a.value_code vrbl
  ,ROUND(b.value_ind / a.value_ind, 2) value_ind
FROM tea.data a
LEFT JOIN tea.data b ON a.year = b.year
  AND a.level_w = b.level_w
  AND a.code_h = b.code_h
  AND a.code_w = b.code_w
  AND a.brdwn = b.brdwn
  AND a.brdwn_code = b.brdwn_code
WHERE a.year = $1
  AND a.level_w = $4
  AND a.code_h = ''total''
  AND a.brdwn = $6
  AND a.brdwn_code = $7
  AND a.value_code = ''empl_w''
  AND b.value_code = ''value_added''
  AND a.value_ind > 0'
  ,NULL
  ,'Pievienotā vērtība uz vienu darbvietu, €'
  ,'Value added per job, €'
  );

INSERT INTO tea.texts_scatter_axis_menu
VALUES (
  'x'
  ,'va_w'
  ,'Pievienotā vērtība'
  ,'Value added'
  ,'w'
  ,'SELECT year
  ,level_w "level"
  ,code_w code
  ,value_code vrbl
  ,value_ind
FROM tea.data
WHERE year = $1
  AND level_w = $4
  AND code_h = ''total''
  AND brdwn = $6
  AND brdwn_code = $7
  AND value_code = ''value_added'''
  ,'USING _year 1
  ,_level_h 2
  ,_code_h 3
  ,_level_w 4
  ,_code_w 5
  ,_brdwn 6
  ,_brdwn_code 7
  ,_value_code 8
  ,_x 9
  ,_y 10;'
  ,'Pievienotā vērtība, €'
  ,'Value added, €'
  );

INSERT INTO tea.texts_scatter_axis_menu
VALUES (
  'x'
  ,'va_emp'
  ,'Pievienotā vērtība uz vienu nodarbināto'
  ,'Value added per one employed'
  ,'h'
  ,'SELECT a.year
  ,a.level_h "level"
  ,a.code_h code
  ,a.value_code vrbl
  ,ROUND(b.value_ind / a.value_ind, 2) value_ind
FROM tea.data a
LEFT JOIN tea.data b ON a.year = b.year
  AND a.level_w = b.level_w
  AND a.level_h = b.level_h
  AND a.code_h = b.code_h
  AND a.code_w = b.code_w
  AND a.brdwn = b.brdwn
  AND a.brdwn_code = b.brdwn_code
WHERE a.year = $1
  AND a.level_h = $2
  AND a.code_w = ''total''
  AND a.brdwn = $6
  AND a.brdwn_code = $7
  AND a.value_code = ''empl''
  AND b.value_code = ''value_added''
  AND a.value_ind > 0'
  ,NULL
  ,'Pievienotā vērtība uz vienu nodarbināto, €'
  ,'Value added per one employed, €'
  );