DROP TABLE IF EXISTS tea.texts_title_ext;

CREATE TABLE tea.texts_title_ext (
  r_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  ,home_work TEXT NOT NULL
  ,indicator_type TEXT NOT NULL
  ,selected_territ TEXT NOT NULL
  ,ext_percentage_list_title_lv TEXT NOT NULL
  ,ext_percentage_list_title_en TEXT NOT NULL
  ,ext_percentage_list_all_lv TEXT NOT NULL
  ,ext_percentage_list_all_en TEXT NOT NULL
  ,ext_percentage_list_same_lv TEXT NOT NULL
  ,ext_percentage_list_same_en TEXT NOT NULL
  ,ext_percentage_list_out_lv TEXT NOT NULL
  ,ext_percentage_list_out_en TEXT NOT NULL
  ,ext_percentage_list_table_col_2_title_lv TEXT NOT NULL
  ,ext_percentage_list_table_col_2_title_en TEXT NOT NULL
  ,ext_percentage_list_table_col_3_title_lv TEXT NOT NULL
  ,ext_percentage_list_table_col_3_title_en TEXT NOT NULL
  ,ext_percentage_bar_text_lv TEXT NOT NULL
  ,ext_percentage_bar_text_en TEXT NOT NULL
  ,ext_pie_chart_in_txt_lv TEXT NOT NULL
  ,ext_pie_chart_in_txt_en TEXT NOT NULL
  ,ext_pie_chart_out_txt_lv TEXT NOT NULL
  ,ext_pie_chart_out_txt_en TEXT NOT NULL
  ,ext_map_territory_info_title_lv TEXT NOT NULL
  ,ext_map_territory_info_title_en TEXT NOT NULL
  ,ext_map_territory_info_txt1_lv TEXT NOT NULL
  ,ext_map_territory_info_txt1_en TEXT NOT NULL
  ,ext_map_territory_info_txt2_lv TEXT NOT NULL
  ,ext_map_territory_info_txt2_en TEXT NOT NULL
  ,ext_map_territory_info_txt3_lv TEXT
  ,ext_map_territory_info_txt3_en TEXT
  ,ext_lines_chart_txt_all_lv TEXT NOT NULL
  ,ext_lines_chart_txt_all_en TEXT NOT NULL
  ,ext_lines_chart_txt_same_lv TEXT
  ,ext_lines_chart_txt_same_en TEXT
  ,ext_lines_chart_txt_out_lv TEXT
  ,ext_lines_chart_txt_out_en TEXT
  ,ext_flow_chart_title_lv TEXT
  ,ext_flow_chart_title_en TEXT
  ,ext_flow_chart_txt_lv TEXT
  ,ext_flow_chart_txt_en TEXT
  ,ext_flow_chart_others_lv TEXT
  ,ext_flow_chart_others_en TEXT
  ,ext_lines_chart_tab1_lv TEXT NOT NULL
  ,ext_lines_chart_tab1_en TEXT NOT NULL
  ,ext_lines_chart_tab2_lv TEXT NOT NULL
  ,ext_lines_chart_tab2_en TEXT NOT NULL
  ,ext_lines_chart_tab1_x_lv TEXT NOT NULL
  ,ext_lines_chart_tab1_x_en TEXT NOT NULL
  ,ext_lines_chart_tab1_y_lv TEXT NOT NULL
  ,ext_lines_chart_tab1_y_en TEXT NOT NULL
  ,ext_lines_chart_tab2_x_lv TEXT NOT NULL
  ,ext_lines_chart_tab2_x_en TEXT NOT NULL
  ,ext_lines_chart_tab2_y_lv TEXT NOT NULL
  ,ext_lines_chart_tab2_y_en TEXT NOT NULL
  ,ext_lines_chart_tab1_title_lv TEXT NOT NULL
  ,ext_lines_chart_tab1_title_en TEXT NOT NULL
  ,ext_lines_chart_tab2_title_lv TEXT NOT NULL
  ,ext_lines_chart_tab2_title_en TEXT NOT NULL
  );

ALTER TABLE tea.texts_title_ext OWNER TO tea_dev;

GRANT SELECT
  ON TABLE tea.texts_title_ext
  TO vdvv_web
    ,editor_texts
    ,admin_texts;

GRANT UPDATE
  ON TABLE tea.texts_title_ext
  TO editor_texts
    ,admin_texts;

GRANT DELETE
  ,INSERT
  ON TABLE tea.texts_title_ext
  TO admin_texts;

INSERT INTO tea.texts_title_ext (
  home_work
  ,indicator_type
  ,selected_territ
  ,ext_percentage_list_title_lv
  ,ext_percentage_list_title_en
  ,ext_percentage_list_all_lv
  ,ext_percentage_list_all_en
  ,ext_percentage_list_same_lv
  ,ext_percentage_list_same_en
  ,ext_percentage_list_out_lv
  ,ext_percentage_list_out_en
  ,ext_percentage_list_table_col_2_title_lv
  ,ext_percentage_list_table_col_2_title_en
  ,ext_percentage_list_table_col_3_title_lv
  ,ext_percentage_list_table_col_3_title_en
  ,ext_percentage_bar_text_lv
  ,ext_percentage_bar_text_en
  ,ext_pie_chart_in_txt_lv
  ,ext_pie_chart_in_txt_en
  ,ext_pie_chart_out_txt_lv
  ,ext_pie_chart_out_txt_en
  ,ext_map_territory_info_title_lv
  ,ext_map_territory_info_title_en
  ,ext_map_territory_info_txt1_lv
  ,ext_map_territory_info_txt1_en
  ,ext_map_territory_info_txt2_lv
  ,ext_map_territory_info_txt2_en
  ,ext_map_territory_info_txt3_lv
  ,ext_map_territory_info_txt3_en
  ,ext_lines_chart_txt_all_lv
  ,ext_lines_chart_txt_all_en
  ,ext_lines_chart_txt_same_lv
  ,ext_lines_chart_txt_same_en
  ,ext_lines_chart_txt_out_lv
  ,ext_lines_chart_txt_out_en
  ,ext_flow_chart_title_lv
  ,ext_flow_chart_title_en
  ,ext_flow_chart_txt_lv
  ,ext_flow_chart_txt_en
  ,ext_flow_chart_others_lv
  ,ext_flow_chart_others_en
  ,ext_lines_chart_tab1_lv
  ,ext_lines_chart_tab1_en
  ,ext_lines_chart_tab2_lv
  ,ext_lines_chart_tab2_en
  ,ext_lines_chart_tab1_x_lv
  ,ext_lines_chart_tab1_x_en
  ,ext_lines_chart_tab1_y_lv
  ,ext_lines_chart_tab1_y_en
  ,ext_lines_chart_tab2_x_lv
  ,ext_lines_chart_tab2_x_en
  ,ext_lines_chart_tab2_y_lv
  ,ext_lines_chart_tab2_y_en
  ,ext_lines_chart_tab1_title_lv
  ,ext_lines_chart_tab1_title_en
  ,ext_lines_chart_tab2_title_lv
  ,ext_lines_chart_tab2_title_en
  )
VALUES (
  'w'
  ,'empl'
  ,'all'
  ,'m_v_c.name_lv_loc,
'' nodarbinātie'''
  ,'''Employed in '',
LOWER(m_v_c.name_en)'
  ,'''Visi'''
  ,'''All'''
  ,'''Vietējie'''
  ,'''Locals'''
  ,'''Dzīvo citur'''
  ,'''Live elsewhere'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''%'''
  ,'''%'''
  ,'''Latvijas iedzīvotāji visbiežāk nodarbināti '',
LOWER(m_b_c.name_lv_loc),
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', main.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvietā''
  ELSE LOWER(m_v_c.name_lv_loc)
  END,
''. Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot.value_ind),
''</b>% no <b>'',
get_pretty_number(''lv'', tot.value_ind),
''</b> Latvijas '',
CASE 
  WHEN get_pretty_number(''lv'', tot.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', tot.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', tot.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvietas''
  ELSE LOWER(m_v_c.name_lv_dat)
  END,
''.'''
  ,'''Employing <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> out of the <b>'',
get_pretty_number(''en'', tot.value_ind),
''</b> individuals who work in Latvia, '',
LOWER(m_v_c.name_en),
'' in the '',
LOWER(m_b_c.name_en),
'' make up the largest part of all '',
LOWER(m_v_c.name_en),
'' in Latvia – <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tot.value_ind),
''</b>%.'''
  ,'''<b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', main.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvietā''
  ELSE LOWER(m_v_c.name_lv_loc)
  END,
'' strādā <b>'',
get_pretty_number(''lv'', empl.value_ind),
''</b> iedzīvotāji, kas dzīvo tajā pašā teritorijā, kur atrodas darbvieta. Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot_empl_w.value_ind),
''</b>% no visām Latvijas '',
LOWER(m_v_c.name_lv_dat),
''.'''
  ,'''The number of '',
LOWER(m_v_c.name_en),
'' employing <b>'',
get_pretty_number(''en'', empl.value_ind),
''</b> individuals who live in their workplace territory totals <b>'',
get_pretty_number(''en'', main.value_ind),
''</b>, representing <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tot_empl_w.value_ind),
''</b>% of all '',
LOWER(m_v_c.name_en),
'' in Latvia.'''
  ,'''<b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> jeb <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot_empl_w.value_ind),
''</b>% no visām Latvijas '',
LOWER(m_v_c.name_lv_dat),
'' (<b>'',
get_pretty_number(''lv'', tot_empl_w.value_ind),
''</b>) strādā iedzīvotāji, kas uz darba vietu dodas no citas teritorijas.'''
  ,'''Out of all '',
LOWER(m_v_c.name_en),
'' in Latvia (<b>'',
get_pretty_number(''en'', tot_empl_w.value_ind),
''</b>), <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> engage individuals who live outside their workplace territory, representing <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tot_empl_w.value_ind),
''</b>%.'''
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'''Iedzīvotāji darbaspējas vecumā (15–64 gadi)'''
  ,'''Working-age population (aged 15–64)'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Uz 100 iedzīvotājiem darbspējas vecumā'''
  ,'''Per 100 inhabitants of working age'''
  ,'''Visi'''
  ,'''All'''
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'m_v_c.name_lv,
'' uz 100 iedzīvotājiem'''
  ,'m_v_c.name_en,
'' per 100 inhabitants'''
  ,'''Gads'''
  ,'''Year'''
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'''Gads'''
  ,'''Year'''
  ,'m_v_c.name_lv,
'' uz 100 iedzīvotājiem'''
  ,'m_v_c.name_en,
'' per 100 inhabitants'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'m_v_c.name_lv,
'' uz 100 iedzīvotājiem darbspējas vecumā'''
  ,'m_v_c.name_en,
'' per 100 inhabitants of working age'''
  );

INSERT INTO tea.texts_title_ext (
  home_work
  ,indicator_type
  ,selected_territ
  ,ext_percentage_list_title_lv
  ,ext_percentage_list_title_en
  ,ext_percentage_list_all_lv
  ,ext_percentage_list_all_en
  ,ext_percentage_list_same_lv
  ,ext_percentage_list_same_en
  ,ext_percentage_list_out_lv
  ,ext_percentage_list_out_en
  ,ext_percentage_list_table_col_2_title_lv
  ,ext_percentage_list_table_col_2_title_en
  ,ext_percentage_list_table_col_3_title_lv
  ,ext_percentage_list_table_col_3_title_en
  ,ext_percentage_bar_text_lv
  ,ext_percentage_bar_text_en
  ,ext_pie_chart_in_txt_lv
  ,ext_pie_chart_in_txt_en
  ,ext_pie_chart_out_txt_lv
  ,ext_pie_chart_out_txt_en
  ,ext_map_territory_info_title_lv
  ,ext_map_territory_info_title_en
  ,ext_map_territory_info_txt1_lv
  ,ext_map_territory_info_txt1_en
  ,ext_map_territory_info_txt2_lv
  ,ext_map_territory_info_txt2_en
  ,ext_map_territory_info_txt3_lv
  ,ext_map_territory_info_txt3_en
  ,ext_lines_chart_txt_all_lv
  ,ext_lines_chart_txt_all_en
  ,ext_lines_chart_txt_same_lv
  ,ext_lines_chart_txt_same_en
  ,ext_lines_chart_txt_out_lv
  ,ext_lines_chart_txt_out_en
  ,ext_flow_chart_title_lv
  ,ext_flow_chart_title_en
  ,ext_flow_chart_txt_lv
  ,ext_flow_chart_txt_en
  ,ext_flow_chart_others_lv
  ,ext_flow_chart_others_en
  ,ext_lines_chart_tab1_lv
  ,ext_lines_chart_tab1_en
  ,ext_lines_chart_tab2_lv
  ,ext_lines_chart_tab2_en
  ,ext_lines_chart_tab1_x_lv
  ,ext_lines_chart_tab1_x_en
  ,ext_lines_chart_tab1_y_lv
  ,ext_lines_chart_tab1_y_en
  ,ext_lines_chart_tab2_x_lv
  ,ext_lines_chart_tab2_x_en
  ,ext_lines_chart_tab2_y_lv
  ,ext_lines_chart_tab2_y_en
  ,ext_lines_chart_tab1_title_lv
  ,ext_lines_chart_tab1_title_en
  ,ext_lines_chart_tab2_title_lv
  ,ext_lines_chart_tab2_title_en
  )
VALUES (
  'w'
  ,'empl'
  ,'selected'
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_loc),
'' nodarbinātie'''
  ,'''Employed in '',
LOWER(m_v_c.name_en),
'' of '',
t.name_en'
  ,'''Visi'''
  ,'''All'''
  ,'''Vietējie'''
  ,'''Locals'''
  ,'''Dzīvo citur'''
  ,'''Live elsewhere'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''%'''
  ,'''%'''
  ,
  't.name_lv_loc,
'' iedzīvotāji visbiežāk nodarbināti '',
LOWER(m_b_c.name_lv_loc),
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', main.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvietā''
  ELSE LOWER(m_v_c.name_lv_loc)
  END,
''. Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot.value_ind),
''</b>% no <b>'',
get_pretty_number(''lv'', tot.value_ind),
''</b> '',
t.name_lv_gen,
'' '',
CASE 
  WHEN get_pretty_number(''lv'', tot.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', tot.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', tot.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvietas''
  ELSE LOWER(m_v_c.name_lv_dat)
  END,
''.'''
  ,'''Employing <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> out of the <b>'',
get_pretty_number(''en'', tot.value_ind),
''</b> individuals who work in '',
t.name_en,
'', '',
LOWER(m_v_c.name_en),
'' in the '',
LOWER(m_b_c.name_en),
'' make up the largest part of all '',
LOWER(m_v_c.name_en),
'' in '',
t.name_en,
'' – <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tot.value_ind),
''</b>%.'''
  ,'''<b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', main.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 2) NOT LIKE ''11''
    THEN ''darbvietā''
  ELSE LOWER(m_v_c.name_lv_loc)
  END,
'' strādā '',
t.name_lv_gen,
'' iedzīvotāji, kas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot_empl_w.value_ind),
''</b>% no visām '',
t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_dat),
''.'''
  ,'''The number of '',
LOWER(m_v_c.name_en),
'' employing residents of '',
t.name_en,
'' totals <b>'',
get_pretty_number(''en'', main.value_ind),
''</b>, making up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tot_empl_w.value_ind),
''</b>% of all '',
LOWER(m_v_c.name_en),
'' in '',
t.name_en,
''.'''
  ,'''<b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> jeb <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot_empl_w.value_ind),
''</b>% no visām '',
t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_dat),
'' (<b>'',
get_pretty_number(''lv'', tot_empl_w.value_ind),
''</b>) strādā iedzīvotāji, kas dzīvo ārpus '',
t.name_lv_gen,
''.'''
  ,'''Out of all '',
LOWER(m_v_c.name_en),
'' in '',
t.name_en,
'' (<b>'',
get_pretty_number(''en'', tot_empl_w.value_ind),
''</b>), <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> engage individuals who live outside '',
t.name_en,
'', representing <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tot_empl_w.value_ind),
''</b>%.'''
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' in '',
t.name_en'
  ,'''Iedzīvotāji darbaspējas vecumā (15–64 gadi)'''
  ,'''Working-age population (aged 15–64)'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Uz 100 iedzīvotājiem darbspējas vecumā'''
  ,'''Per 100 inhabitants of working age'''
  ,'''Visi'''
  ,'''All'''
  ,'''Vietējie'''
  ,'''Locals'''
  ,'''Dzīvo citur'''
  ,'''Live elsewhere'''
  ,'''Ārpus '',
t.name_lv_gen,
'' dzīvojošie nodarbinātie'''
  ,'''Employed who live outside '',
t.name_en'
  ,'''Nodarbināti '',
t.name_lv_loc'
  ,'''Employed in '',
t.name_en'
  ,'''Pārējie ārpus teritorijas dzīvojošie'''
  ,'''Residence in other territory'''
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'m_v_c.name_lv,
'' uz 100 iedzīvotājiem'''
  ,'m_v_c.name_en,
'' per 100 inhabitants'''
  ,'''Gads'''
  ,'''Year'''
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'''Gads'''
  ,'''Year'''
  ,'m_v_c.name_lv,
'' uz 100 iedzīvotājiem'''
  ,'m_v_c.name_en,
'' per 100 inhabitants'''
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_loc),
'' nodarbināto skaits'''
  ,'''Number of employed in '',
LOWER(m_v_c.name_en),
'' of '',
t.name_en'
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_gen),
'' skaits uz 100 iedzīvotājiem darbspējas vecumā'''
  ,'''Number of '',
m_v_c.name_en,
'' in '',
t.name_en,
'' per 100 inhabitants of working age'''
  );

INSERT INTO tea.texts_title_ext (
  home_work
  ,indicator_type
  ,selected_territ
  ,ext_percentage_list_title_lv
  ,ext_percentage_list_title_en
  ,ext_percentage_list_all_lv
  ,ext_percentage_list_all_en
  ,ext_percentage_list_same_lv
  ,ext_percentage_list_same_en
  ,ext_percentage_list_out_lv
  ,ext_percentage_list_out_en
  ,ext_percentage_list_table_col_2_title_lv
  ,ext_percentage_list_table_col_2_title_en
  ,ext_percentage_list_table_col_3_title_lv
  ,ext_percentage_list_table_col_3_title_en
  ,ext_percentage_bar_text_lv
  ,ext_percentage_bar_text_en
  ,ext_pie_chart_in_txt_lv
  ,ext_pie_chart_in_txt_en
  ,ext_pie_chart_out_txt_lv
  ,ext_pie_chart_out_txt_en
  ,ext_map_territory_info_title_lv
  ,ext_map_territory_info_title_en
  ,ext_map_territory_info_txt1_lv
  ,ext_map_territory_info_txt1_en
  ,ext_map_territory_info_txt2_lv
  ,ext_map_territory_info_txt2_en
  ,ext_map_territory_info_txt3_lv
  ,ext_map_territory_info_txt3_en
  ,ext_lines_chart_txt_all_lv
  ,ext_lines_chart_txt_all_en
  ,ext_lines_chart_txt_same_lv
  ,ext_lines_chart_txt_same_en
  ,ext_lines_chart_txt_out_lv
  ,ext_lines_chart_txt_out_en
  ,ext_flow_chart_title_lv
  ,ext_flow_chart_title_en
  ,ext_flow_chart_txt_lv
  ,ext_flow_chart_txt_en
  ,ext_flow_chart_others_lv
  ,ext_flow_chart_others_en
  ,ext_lines_chart_tab1_lv
  ,ext_lines_chart_tab1_en
  ,ext_lines_chart_tab2_lv
  ,ext_lines_chart_tab2_en
  ,ext_lines_chart_tab1_x_lv
  ,ext_lines_chart_tab1_x_en
  ,ext_lines_chart_tab1_y_lv
  ,ext_lines_chart_tab1_y_en
  ,ext_lines_chart_tab2_x_lv
  ,ext_lines_chart_tab2_x_en
  ,ext_lines_chart_tab2_y_lv
  ,ext_lines_chart_tab2_y_en
  ,ext_lines_chart_tab1_title_lv
  ,ext_lines_chart_tab1_title_en
  ,ext_lines_chart_tab2_title_lv
  ,ext_lines_chart_tab2_title_en
  )
VALUES (
  'w'
  ,'other'
  ,'selected'
  ,'t.name_lv_gen,
'' darbvietās radītā '',
LOWER(m_v_c.name_lv_loc)'
  ,'m_v_c.name_en,
'' in jobs of '',
t.name_en'
  ,'''Visi'''
  ,'''All'''
  ,'''Vietējie'''
  ,'''Locals'''
  ,'''Dzīvo citur'''
  ,'''Live elsewhere'''
  ,'''Tūkst. €'''
  ,'''Thsd €'''
  ,'''%'''
  ,'''%'''
  ,'t.name_lv_gen,
'' darbvietās vislielākā gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir '',
LOWER(m_b_c.name_lv_loc),
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / tot_empl_w.value_ind),
''</b> € uz vienu darbvietu. Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot.value_ind),
''</b>% no kopējās '',
t.name_lv_gen,
'' darbvietās radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', tot.value_ind),
''</b> €).'''
  ,'''The jobs in '',
t.name_en,
'' generate the highest annual '',
LOWER(m_v_c.name_en),
'' in '',
LOWER(m_b_c.name_en),
''. It amounts to € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> (€ <b>'',
get_pretty_number(''en'', main.value_ind / tot_empl_w.value_ind),
''</b> per one job) and represents <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tot.value_ind),
''</b>% of the total annual '',
LOWER(m_v_c.name_en),
'' in '',
t.name_en,
'' (€ <b>'',
get_pretty_number(''en'', tot.value_ind),
''</b>).'''
  ,'t.name_lv_gen,
'' darbvietās nodarbināto vietējo iedzīvotāju gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel_w.value_ind),
''</b> € uz vienu darbvietu. Tas veido <b>'',
get_pretty_number(''lv'', main.pct),
''</b>% no kopējās '',
t.name_lv_loc,
'' gada laikā radītās '',
LOWER(m_v_c.name_lv_gen),
''.'''
  ,'''The local individuals who work in jobs of '',
t.name_en,
'' but live elsewhere annually generate '',
LOWER(m_v_c.name_en),
'' amounting to € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> (€ <b>'',
get_pretty_number(''en'', main.value_ind / rel_w.value_ind),
''</b> per one job). This represents <b>'',
get_pretty_number(''en'', main.pct),
''</b>% of the total annual '',
LOWER(m_v_c.name_en),
'' in '',
t.name_en,
''.'''
  ,'t.name_lv_gen,
'' darbvietās nodarbināto ārpus teritorijas dzīvojošo iedzīvotāju gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel_w.value_ind),
''</b> € uz vienu darbvietu. Tas veido <b>'',
get_pretty_number(''lv'', main.pct),
''</b>% no kopējās '',
t.name_lv_loc,
'' gada laikā radītās '',
LOWER(m_v_c.name_lv_gen),
''.'''
  ,'''The individuals who work in jobs of '',
t.name_en,
'' but live elsewhere annually generate '',
LOWER(m_v_c.name_en),
'' amounting to € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> (€ <b>'',
get_pretty_number(''en'', main.value_ind / rel_w.value_ind),
''</b> per one job). This represents <b>'',
get_pretty_number(''en'', main.pct),
''</b>% of the total annual '',
LOWER(m_v_c.name_en),
'' in '',
t.name_en,
''.'''
  ,'t.name_lv_gen,
'' darbvietās nodarbināto iedzīvotāju radītā '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' generated by employed in jobs in '',
t.name_en'
  ,'''Darbvietās gada laikā radītā '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' generated in jobs during the year'''
  ,'''Uz vienu darbvietu'''
  ,'''Per one job'''
  ,NULL
  ,NULL
  ,'''Visi'''
  ,'''All'''
  ,'''Vietējie'''
  ,'''Locals'''
  ,'''Dzīvo citur'''
  ,'''Live elsewhere'''
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'m_v_c.name_lv,
'' uz darbvietu'''
  ,'m_v_c.name_en,
'' per job'''
  ,'''Gads'''
  ,'''Year'''
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'''Gads'''
  ,'''Year'''
  ,'m_v_c.name_lv,
'' uz darbvietu'''
  ,'m_v_c.name_en,
'' per job'''
  ,'t.name_lv_gen,
'' darbvietās gada laikā radītā '',
LOWER(m_v_c.name_lv),
'', tūkst. €'''
  ,'m_v_c.name_en,
'', generated over the year in jobs of  '',
t.name_en,
'', thsd €'''
  ,'m_v_c.name_lv,
'' uz darbvietu '',
t.name_lv_loc,
'', €'''
  ,'m_v_c.name_en,
'' per one job in '',
t.name_en,
'', €'''
  );

INSERT INTO tea.texts_title_ext (
  home_work
  ,indicator_type
  ,selected_territ
  ,ext_percentage_list_title_lv
  ,ext_percentage_list_title_en
  ,ext_percentage_list_all_lv
  ,ext_percentage_list_all_en
  ,ext_percentage_list_same_lv
  ,ext_percentage_list_same_en
  ,ext_percentage_list_out_lv
  ,ext_percentage_list_out_en
  ,ext_percentage_list_table_col_2_title_lv
  ,ext_percentage_list_table_col_2_title_en
  ,ext_percentage_list_table_col_3_title_lv
  ,ext_percentage_list_table_col_3_title_en
  ,ext_percentage_bar_text_lv
  ,ext_percentage_bar_text_en
  ,ext_pie_chart_in_txt_lv
  ,ext_pie_chart_in_txt_en
  ,ext_pie_chart_out_txt_lv
  ,ext_pie_chart_out_txt_en
  ,ext_map_territory_info_title_lv
  ,ext_map_territory_info_title_en
  ,ext_map_territory_info_txt1_lv
  ,ext_map_territory_info_txt1_en
  ,ext_map_territory_info_txt2_lv
  ,ext_map_territory_info_txt2_en
  ,ext_map_territory_info_txt3_lv
  ,ext_map_territory_info_txt3_en
  ,ext_lines_chart_txt_all_lv
  ,ext_lines_chart_txt_all_en
  ,ext_lines_chart_txt_same_lv
  ,ext_lines_chart_txt_same_en
  ,ext_lines_chart_txt_out_lv
  ,ext_lines_chart_txt_out_en
  ,ext_flow_chart_title_lv
  ,ext_flow_chart_title_en
  ,ext_flow_chart_txt_lv
  ,ext_flow_chart_txt_en
  ,ext_flow_chart_others_lv
  ,ext_flow_chart_others_en
  ,ext_lines_chart_tab1_lv
  ,ext_lines_chart_tab1_en
  ,ext_lines_chart_tab2_lv
  ,ext_lines_chart_tab2_en
  ,ext_lines_chart_tab1_x_lv
  ,ext_lines_chart_tab1_x_en
  ,ext_lines_chart_tab1_y_lv
  ,ext_lines_chart_tab1_y_en
  ,ext_lines_chart_tab2_x_lv
  ,ext_lines_chart_tab2_x_en
  ,ext_lines_chart_tab2_y_lv
  ,ext_lines_chart_tab2_y_en
  ,ext_lines_chart_tab1_title_lv
  ,ext_lines_chart_tab1_title_en
  ,ext_lines_chart_tab2_title_lv
  ,ext_lines_chart_tab2_title_en
  )
VALUES (
  'h'
  ,'other'
  ,'all'
  ,'''Nodarbināto iedzīvotāju radītā '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' generated by employed'''
  ,'''Visi'''
  ,'''All'''
  ,'''Strādā turpat'''
  ,'''Work locally'''
  ,'''Strādā citur'''
  ,'''Work elsewhere'''
  ,'''Tūkst. €'''
  ,'''Thsd €'''
  ,'''%'''
  ,'''%'''
  ,'''Latvijas iedzīvotāju vislielākā gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir '',
LOWER(m_b_c.name_lv_loc),
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / tot_empl.value_ind),
''</b> € uz vienu nodarbināto. Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot.value_ind),
''</b>% no kopējās Latvijas iedzīvotāju radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', tot.value_ind),
''</b> €).'''
  ,'''The employed residents of Latvia generate the highest annual '',
LOWER(m_v_c.name_en),
'' in '',
LOWER(m_b_c.name_en),
''. It amounts to € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> (€ <b>'',
get_pretty_number(''en'', main.value_ind / tot_empl.value_ind),
''</b> per one employed) and represents <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tot.value_ind),
''</b>% of the total annual '',
LOWER(m_v_c.name_en),
'' generated by the employed residents of Latvia (€ <b>'',
get_pretty_number(''en'', tot.value_ind),
''</b>).'''
  ,'''Iedzīvotāju, kas dzīvo tajā pašā teritorijā, kur atrodas darbvieta, radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> €. Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot.value_ind),
''</b>% no visās Latvijas darbvietās radītās '',
LOWER(m_v_c.name_lv_gen),
''.'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year by the resident population that live in the same territory where job is located, is € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b>. This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tot.value_ind),
''</b>% of the total annual '',
LOWER(m_v_c.name_en),
'' generated in the jobs of Latvia.'''
  ,'''Iedzīvotāju, kas dzīvo ārpus teritorijas, kur atrodas darbvieta, radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> €. Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot.value_ind),
''</b>% no visās Latvijas darbvietās radītās '',
LOWER(m_v_c.name_lv_gen),
''.'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year by the '',
LOWER(m_v_c.name_en),
'' that live outside the territory where job is located, is € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b>. This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tot.value_ind),
''</b>% of the total annual '',
LOWER(m_v_c.name_en),
'' generated in the jobs of Latvia.'''
  ,'''Nodarbināto iedzīvotāju radītā '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' generated by employed'''
  ,'''Nodarbināto gada laikā radītā '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' generated by employed during the year'''
  ,'''Uz vienu nodarbināto'''
  ,'''Per one employed'''
  ,NULL
  ,NULL
  ,'''Visi'''
  ,'''All'''
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'m_v_c.name_lv,
'' uz nodarbināto'''
  ,'m_v_c.name_en,
'' per employee'''
  ,'''Gads'''
  ,'''Year'''
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'''Gads'''
  ,'''Year'''
  ,'m_v_c.name_lv,
'' uz nodarbināto'''
  ,'m_v_c.name_en,
'' per employee'''
  ,'''Nodarbināto iedzīvotāju gada laikā radītā '',
LOWER(m_v_c.name_lv),
'', tūkst. €'''
  ,'m_v_c.name_en,
'', generated over the year by employed, thsd €'''
  ,'m_v_c.name_lv,
'' uz nodarbināto, €'''
  ,'m_v_c.name_en,
'' per one employed, €'''
  );

INSERT INTO tea.texts_title_ext (
  home_work
  ,indicator_type
  ,selected_territ
  ,ext_percentage_list_title_lv
  ,ext_percentage_list_title_en
  ,ext_percentage_list_all_lv
  ,ext_percentage_list_all_en
  ,ext_percentage_list_same_lv
  ,ext_percentage_list_same_en
  ,ext_percentage_list_out_lv
  ,ext_percentage_list_out_en
  ,ext_percentage_list_table_col_2_title_lv
  ,ext_percentage_list_table_col_2_title_en
  ,ext_percentage_list_table_col_3_title_lv
  ,ext_percentage_list_table_col_3_title_en
  ,ext_percentage_bar_text_lv
  ,ext_percentage_bar_text_en
  ,ext_pie_chart_in_txt_lv
  ,ext_pie_chart_in_txt_en
  ,ext_pie_chart_out_txt_lv
  ,ext_pie_chart_out_txt_en
  ,ext_map_territory_info_title_lv
  ,ext_map_territory_info_title_en
  ,ext_map_territory_info_txt1_lv
  ,ext_map_territory_info_txt1_en
  ,ext_map_territory_info_txt2_lv
  ,ext_map_territory_info_txt2_en
  ,ext_map_territory_info_txt3_lv
  ,ext_map_territory_info_txt3_en
  ,ext_lines_chart_txt_all_lv
  ,ext_lines_chart_txt_all_en
  ,ext_lines_chart_txt_same_lv
  ,ext_lines_chart_txt_same_en
  ,ext_lines_chart_txt_out_lv
  ,ext_lines_chart_txt_out_en
  ,ext_flow_chart_title_lv
  ,ext_flow_chart_title_en
  ,ext_flow_chart_txt_lv
  ,ext_flow_chart_txt_en
  ,ext_flow_chart_others_lv
  ,ext_flow_chart_others_en
  ,ext_lines_chart_tab1_lv
  ,ext_lines_chart_tab1_en
  ,ext_lines_chart_tab2_lv
  ,ext_lines_chart_tab2_en
  ,ext_lines_chart_tab1_x_lv
  ,ext_lines_chart_tab1_x_en
  ,ext_lines_chart_tab1_y_lv
  ,ext_lines_chart_tab1_y_en
  ,ext_lines_chart_tab2_x_lv
  ,ext_lines_chart_tab2_x_en
  ,ext_lines_chart_tab2_y_lv
  ,ext_lines_chart_tab2_y_en
  ,ext_lines_chart_tab1_title_lv
  ,ext_lines_chart_tab1_title_en
  ,ext_lines_chart_tab2_title_lv
  ,ext_lines_chart_tab2_title_en
  )
VALUES (
  'w'
  ,'other'
  ,'all'
  ,'''Darbvietās radītā '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' in jobs'''
  ,'''Visi'''
  ,'''All'''
  ,'''Vietējie'''
  ,'''Locals'''
  ,'''Dzīvo citur'''
  ,'''Live elsewhere'''
  ,'''Tūkst. €'''
  ,'''Thsd €'''
  ,'''%'''
  ,'''%'''
  ,'''Latvijas darbvietās vislielākā gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir '',
LOWER(m_b_c.name_lv_loc),
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / tot_empl_w.value_ind),
''</b> € uz vienu darbvietu. Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot.value_ind),
''</b>% no kopējās Latvijas darbvietās radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', tot.value_ind),
''</b> €).'''
  ,'''The jobs in Latvia generate the highest annual '',
LOWER(m_v_c.name_en),
'' in '',
LOWER(m_b_c.name_en),
''. It amounts to € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> (€ <b>'',
get_pretty_number(''en'', main.value_ind / tot_empl_w.value_ind),
''</b> per one job) and represents <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tot.value_ind),
''</b>% of the total annual '',
LOWER(m_v_c.name_en),
'' in Latvia (€ <b>'',
get_pretty_number(''en'', tot.value_ind),
''</b>).'''
  ,'''Latvijas darbvietās nodarbināto vietējo iedzīvotāju gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> €. Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot.value_ind),
''</b>% no visās Latvijas darbvietās radītās '',
LOWER(m_v_c.name_lv_gen),
''.'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year by the local resident population who are employed in the jobs of Latvia, is € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b>. This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tot.value_ind),
''</b>% of the total annual '',
LOWER(m_v_c.name_en),
'' generated in the jobs of Latvia.'''
  ,'''Latvijas darbvietās nodarbināto ārpus teritorijas dzīvojošo iedzīvotāju gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> €. Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot.value_ind),
''</b>% no visās Latvijas darbvietās radītās '',
LOWER(m_v_c.name_lv_gen),
''.'''
  ,'''The '',
LOWER(m_v_c.name_en),
'', generated over the year in the jobs of Latvia by the resident population that live outside the territory where job is located, is € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b>. This makes up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tot.value_ind),
''</b>% of the total annual '',
LOWER(m_v_c.name_en),
'' generated in the jobs of Latvia.'''
  ,'''Darbvietās nodarbināto iedzīvotāju radītā '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' generated by employed in jobs'''
  ,'''Darbvietās gada laikā radītā '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' generated in jobs during the year'''
  ,'''Uz vienu darbvietu'''
  ,'''Per one job'''
  ,NULL
  ,NULL
  ,'''Visi'''
  ,'''All'''
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'m_v_c.name_lv,
'' uz darbvietu'''
  ,'m_v_c.name_en,
'' per job'''
  ,'''Gads'''
  ,'''Year'''
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'''Gads'''
  ,'''Year'''
  ,'m_v_c.name_lv,
'' uz darbvietu'''
  ,'m_v_c.name_en,
'' per job'''
  ,'''Darbvietās gada laikā radītā '',
LOWER(m_v_c.name_lv),
'', tūkst. €'''
  ,'m_v_c.name_en,
'', generated over the year in jobs, thsd €'''
  ,'m_v_c.name_lv,
'' uz darbvietu, €'''
  ,'m_v_c.name_en,
'' per one job, €'''
  );

INSERT INTO tea.texts_title_ext (
  home_work
  ,indicator_type
  ,selected_territ
  ,ext_percentage_list_title_lv
  ,ext_percentage_list_title_en
  ,ext_percentage_list_all_lv
  ,ext_percentage_list_all_en
  ,ext_percentage_list_same_lv
  ,ext_percentage_list_same_en
  ,ext_percentage_list_out_lv
  ,ext_percentage_list_out_en
  ,ext_percentage_list_table_col_2_title_lv
  ,ext_percentage_list_table_col_2_title_en
  ,ext_percentage_list_table_col_3_title_lv
  ,ext_percentage_list_table_col_3_title_en
  ,ext_percentage_bar_text_lv
  ,ext_percentage_bar_text_en
  ,ext_pie_chart_in_txt_lv
  ,ext_pie_chart_in_txt_en
  ,ext_pie_chart_out_txt_lv
  ,ext_pie_chart_out_txt_en
  ,ext_map_territory_info_title_lv
  ,ext_map_territory_info_title_en
  ,ext_map_territory_info_txt1_lv
  ,ext_map_territory_info_txt1_en
  ,ext_map_territory_info_txt2_lv
  ,ext_map_territory_info_txt2_en
  ,ext_map_territory_info_txt3_lv
  ,ext_map_territory_info_txt3_en
  ,ext_lines_chart_txt_all_lv
  ,ext_lines_chart_txt_all_en
  ,ext_lines_chart_txt_same_lv
  ,ext_lines_chart_txt_same_en
  ,ext_lines_chart_txt_out_lv
  ,ext_lines_chart_txt_out_en
  ,ext_flow_chart_title_lv
  ,ext_flow_chart_title_en
  ,ext_flow_chart_txt_lv
  ,ext_flow_chart_txt_en
  ,ext_flow_chart_others_lv
  ,ext_flow_chart_others_en
  ,ext_lines_chart_tab1_lv
  ,ext_lines_chart_tab1_en
  ,ext_lines_chart_tab2_lv
  ,ext_lines_chart_tab2_en
  ,ext_lines_chart_tab1_x_lv
  ,ext_lines_chart_tab1_x_en
  ,ext_lines_chart_tab1_y_lv
  ,ext_lines_chart_tab1_y_en
  ,ext_lines_chart_tab2_x_lv
  ,ext_lines_chart_tab2_x_en
  ,ext_lines_chart_tab2_y_lv
  ,ext_lines_chart_tab2_y_en
  ,ext_lines_chart_tab1_title_lv
  ,ext_lines_chart_tab1_title_en
  ,ext_lines_chart_tab2_title_lv
  ,ext_lines_chart_tab2_title_en
  )
VALUES (
  'h'
  ,'other'
  ,'selected'
  ,'t.name_lv_gen,
'' nodarbināto iedzīvotāju radītā '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' generated by employed of '',
t.name_en'
  ,'''Visi'''
  ,'''All'''
  ,'''Strādā turpat'''
  ,'''Work locally'''
  ,'''Strādā citur'''
  ,'''Work elsewhere'''
  ,'''Tūkst. €'''
  ,'''Thsd €'''
  ,'''%'''
  ,'''%'''
  ,'t.name_lv_gen,
'' iedzīvotāju vislielākā gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir '',
LOWER(m_b_c.name_lv_loc),
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / tot_empl.value_ind),
''</b> € uz vienu nodarbināto. Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot.value_ind),
''</b>% no kopējās '',
t.name_lv_gen,
'' iedzīvotāju radītās '',
LOWER(m_v_c.name_lv_gen),
'' (<b>'',
get_pretty_number(''lv'', tot.value_ind),
''</b> €).'''
  ,'''The employed residents of '',
t.name_en,
'' generate the highest annual '',
LOWER(m_v_c.name_en),
'' in '',
LOWER(m_b_c.name_en),
''. It amounts to € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> (€ <b>'',
get_pretty_number(''en'', main.value_ind / tot_empl.value_ind),
''</b> per one employed) and represents <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tot.value_ind),
''</b>% of the total annual '',
LOWER(m_v_c.name_en),
'' generated by the employed residents of '',
t.name_en,
'' (€ <b>'',
get_pretty_number(''en'', tot.value_ind),
''</b>).'''
  ,'t.name_lv_gen,
'' iedzīvotāju, kas strādā savas dzīvesvietas teritorijā, gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel.value_ind),
''</b> € uz vienu nodarbināto. Tas veido <b>'',
get_pretty_number(''lv'', main.pct),
''</b>% no kopējās '',
t.name_lv_gen,
'' iedzīvotāju gada laikā radītās '',
LOWER(m_v_c.name_lv_gen),
''.'''
  ,'''The employed residents of '',
t.name_en,
'' who work in their territory of residence annually generate '',
LOWER(m_v_c.name_en),
'' amounting to € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> (€ <b>'',
get_pretty_number(''en'', main.value_ind / rel.value_ind),
''</b> per one employed). This represents <b>'',
get_pretty_number(''en'', main.pct),
''</b>% of the total annual '',
LOWER(m_v_c.name_en),
'' generated by employed residents of '',
t.name_en,
''.'''
  ,'t.name_lv_gen,
'' iedzīvotāju, kas strādā ārpus savas dzīvesvietas teritorijas, gada laikā radītā '',
LOWER(m_v_c.name_lv),
'' ir <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> € jeb <b>'',
get_pretty_number(''lv'', main.value_ind / rel.value_ind),
''</b> € uz vienu nodarbināto. Tas veido <b>'',
get_pretty_number(''lv'', main.pct),
''</b>% no kopējās '',
t.name_lv_gen,
'' iedzīvotāju gada laikā radītās '',
LOWER(m_v_c.name_lv_gen),
''.'''
  ,'''The employed residents of '',
t.name_en,
'' who work outside their territory of residence annually generate '',
LOWER(m_v_c.name_en),
'' amounting to € <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> (€ <b>'',
get_pretty_number(''en'', main.value_ind / rel.value_ind),
''</b> per one employed). This represents <b>'',
get_pretty_number(''en'', main.pct),
''</b>% of the total annual '',
LOWER(m_v_c.name_en),
'' generated by employed residents of '',
t.name_en,
''.'''
  ,'t.name_lv_gen,
'' nodarbināto iedzīvotāju radītā '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' generated by employed of '',
t.name_en'
  ,'''Nodarbināto gada laikā radītā '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' generated by employed during the year'''
  ,'''Uz vienu nodarbināto'''
  ,'''Per one employed'''
  ,NULL
  ,NULL
  ,'''Visi'''
  ,'''All'''
  ,'''Strādā turpat'''
  ,'''Work locally'''
  ,'''Strādā citur'''
  ,'''Work elsewhere'''
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'m_v_c.name_lv,
'' uz nodarbināto'''
  ,'m_v_c.name_en,
'' per employee'''
  ,'''Gads'''
  ,'''Year'''
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'''Gads'''
  ,'''Year'''
  ,'m_v_c.name_lv,
'' uz nodarbināto'''
  ,'m_v_c.name_en,
'' per employee'''
  ,'t.name_lv_gen,
'' nodarbināto iedzīvotāju gada laikā radītā '',
LOWER(m_v_c.name_lv),
'', tūkst. €'''
  ,'m_v_c.name_en,
'', generated over the year by employed in '',
t.name_en,
'', thsd €'''
  ,'m_v_c.name_lv,
'' uz nodarbināto '',
t.name_lv_loc,
'', €'''
  ,'m_v_c.name_en,
'' per one employed in '',
t.name_en,
'', €'''
  );

INSERT INTO tea.texts_title_ext (
  home_work
  ,indicator_type
  ,selected_territ
  ,ext_percentage_list_title_lv
  ,ext_percentage_list_title_en
  ,ext_percentage_list_all_lv
  ,ext_percentage_list_all_en
  ,ext_percentage_list_same_lv
  ,ext_percentage_list_same_en
  ,ext_percentage_list_out_lv
  ,ext_percentage_list_out_en
  ,ext_percentage_list_table_col_2_title_lv
  ,ext_percentage_list_table_col_2_title_en
  ,ext_percentage_list_table_col_3_title_lv
  ,ext_percentage_list_table_col_3_title_en
  ,ext_percentage_bar_text_lv
  ,ext_percentage_bar_text_en
  ,ext_pie_chart_in_txt_lv
  ,ext_pie_chart_in_txt_en
  ,ext_pie_chart_out_txt_lv
  ,ext_pie_chart_out_txt_en
  ,ext_map_territory_info_title_lv
  ,ext_map_territory_info_title_en
  ,ext_map_territory_info_txt1_lv
  ,ext_map_territory_info_txt1_en
  ,ext_map_territory_info_txt2_lv
  ,ext_map_territory_info_txt2_en
  ,ext_map_territory_info_txt3_lv
  ,ext_map_territory_info_txt3_en
  ,ext_lines_chart_txt_all_lv
  ,ext_lines_chart_txt_all_en
  ,ext_lines_chart_txt_same_lv
  ,ext_lines_chart_txt_same_en
  ,ext_lines_chart_txt_out_lv
  ,ext_lines_chart_txt_out_en
  ,ext_flow_chart_title_lv
  ,ext_flow_chart_title_en
  ,ext_flow_chart_txt_lv
  ,ext_flow_chart_txt_en
  ,ext_flow_chart_others_lv
  ,ext_flow_chart_others_en
  ,ext_lines_chart_tab1_lv
  ,ext_lines_chart_tab1_en
  ,ext_lines_chart_tab2_lv
  ,ext_lines_chart_tab2_en
  ,ext_lines_chart_tab1_x_lv
  ,ext_lines_chart_tab1_x_en
  ,ext_lines_chart_tab1_y_lv
  ,ext_lines_chart_tab1_y_en
  ,ext_lines_chart_tab2_x_lv
  ,ext_lines_chart_tab2_x_en
  ,ext_lines_chart_tab2_y_lv
  ,ext_lines_chart_tab2_y_en
  ,ext_lines_chart_tab1_title_lv
  ,ext_lines_chart_tab1_title_en
  ,ext_lines_chart_tab2_title_lv
  ,ext_lines_chart_tab2_title_en
  )
VALUES (
  'h'
  ,'empl'
  ,'selected'
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' of '',
t.name_en'
  ,'''Visi'''
  ,'''All'''
  ,'''Strādā turpat'''
  ,'''Work locally'''
  ,'''Strādā citur'''
  ,'''Work elsewhere'''
  ,'''Skaits'''
  ,'''Number'''
  ,'''%'''
  ,'''%'''
  ,
  't.name_lv_gen,
'' iedzīvotāji visbiežāk strādā '',
LOWER(m_b_c.name_lv_loc),
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', main.value_ind) LIKE ''% %''
    THEN ''nodarbināto''
  WHEN RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 2) NOT LIKE ''11''
    THEN ''nodarbinātais''
  ELSE ''nodarbinātie''
  END,
''. Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot.value_ind),
''</b>% no <b>'',
get_pretty_number(''lv'', tot.value_ind),
''</b> '',
t.name_lv_gen,
'' '',
CASE 
  WHEN get_pretty_number(''lv'', tot.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', tot.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', tot.value_ind), 2) NOT LIKE ''11''
    THEN ''nodarbinātā iedzīvotāja''
  ELSE LOWER(m_v_c.name_lv_dat)
  END,
''.'''
  ,'''Engaging <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> out of the <b>'',
get_pretty_number(''en'', tot.value_ind),
''</b> '',
LOWER(m_v_c.name_en),
'' of '',
t.name_en,
'', businesses of the '',
LOWER(m_b_c.name_en),
'' employ the largest part of the '',
t.name_en,
'' residents – <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tot.value_ind),
''</b>%.'''
  ,'''<b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> jeb <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot_empl.value_ind),
''</b>% no visiem '',
t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_dat),
'' strādā savas dzīvesvietas teritorijā.'''
  ,'''The number of individuals who work in the territory of their residence totals <b>'',
get_pretty_number(''en'', main.value_ind),
''</b>, making up <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tot_empl.value_ind),
''</b>% of all '',
LOWER(m_v_c.name_en),
'' of '',
t.name_en,
''.'''
  ,'''<b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> jeb <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot_empl.value_ind),
''</b>% no visiem '',
t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_dat),
'' (<b>'',
get_pretty_number(''lv'', tot_empl.value_ind),
''</b>) strādā ārpus dzīvesvietas teritorijas.'''
  ,'''Out of all '',
LOWER(m_v_c.name_en),
'' of '',
t.name_en,
'' (<b>'',
get_pretty_number(''en'', tot_empl.value_ind),
''</b>), <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> work outside their territory of residence, representing <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tot_empl.value_ind),
''</b>%.'''
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv)'
  ,'m_v_c.name_en,
'' of '',
t.name_en'
  ,'''Iedzīvotāji darbaspējas vecumā (15–64 gadi)'''
  ,'''Working-age population (aged 15–64)'''
  ,'''No tiem nodarbināti'''
  ,'''Of these employed'''
  ,'''Nodarbinātības līmenis'''
  ,'''Employment rate'''
  ,'''Visi'''
  ,'''All'''
  ,'''Strādā turpat'''
  ,'''Work locally'''
  ,'''Strādā citur'''
  ,'''Work elsewhere'''
  ,'t.name_lv_gen,
'' nodarbinātie iedzīvotāji, kas strādā ārpus šīs teritorijas'''
  ,'''Employed residents of '',
t.name_en,
'' who work outside this territory'''
  ,'''Dzīvo '',
t.name_lv_loc'
  ,'''Live in '',
t.name_en'
  ,'''Darba vieta citur'''
  ,'''Work elsewhere'''
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'''Nodarbinātības līmenis'''
  ,'''Employment rate'''
  ,'''Gads'''
  ,'''Year'''
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'''Gads'''
  ,'''Year'''
  ,'''Nodarbinātības līmenis'''
  ,'''Employment rate'''
  ,'t.name_lv_gen,
'' '',
LOWER(m_v_c.name_lv_gen),
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en),
'' in '',
t.name_en'
  ,'''Nodarbinātības līmenis '',
t.name_lv_loc,
'', %'''
  ,'''Employment rate in '',
t.name_en,
'', %'''
  );

INSERT INTO tea.texts_title_ext (
  home_work
  ,indicator_type
  ,selected_territ
  ,ext_percentage_list_title_lv
  ,ext_percentage_list_title_en
  ,ext_percentage_list_all_lv
  ,ext_percentage_list_all_en
  ,ext_percentage_list_same_lv
  ,ext_percentage_list_same_en
  ,ext_percentage_list_out_lv
  ,ext_percentage_list_out_en
  ,ext_percentage_list_table_col_2_title_lv
  ,ext_percentage_list_table_col_2_title_en
  ,ext_percentage_list_table_col_3_title_lv
  ,ext_percentage_list_table_col_3_title_en
  ,ext_percentage_bar_text_lv
  ,ext_percentage_bar_text_en
  ,ext_pie_chart_in_txt_lv
  ,ext_pie_chart_in_txt_en
  ,ext_pie_chart_out_txt_lv
  ,ext_pie_chart_out_txt_en
  ,ext_map_territory_info_title_lv
  ,ext_map_territory_info_title_en
  ,ext_map_territory_info_txt1_lv
  ,ext_map_territory_info_txt1_en
  ,ext_map_territory_info_txt2_lv
  ,ext_map_territory_info_txt2_en
  ,ext_map_territory_info_txt3_lv
  ,ext_map_territory_info_txt3_en
  ,ext_lines_chart_txt_all_lv
  ,ext_lines_chart_txt_all_en
  ,ext_lines_chart_txt_same_lv
  ,ext_lines_chart_txt_same_en
  ,ext_lines_chart_txt_out_lv
  ,ext_lines_chart_txt_out_en
  ,ext_flow_chart_title_lv
  ,ext_flow_chart_title_en
  ,ext_flow_chart_txt_lv
  ,ext_flow_chart_txt_en
  ,ext_flow_chart_others_lv
  ,ext_flow_chart_others_en
  ,ext_lines_chart_tab1_lv
  ,ext_lines_chart_tab1_en
  ,ext_lines_chart_tab2_lv
  ,ext_lines_chart_tab2_en
  ,ext_lines_chart_tab1_x_lv
  ,ext_lines_chart_tab1_x_en
  ,ext_lines_chart_tab1_y_lv
  ,ext_lines_chart_tab1_y_en
  ,ext_lines_chart_tab2_x_lv
  ,ext_lines_chart_tab2_x_en
  ,ext_lines_chart_tab2_y_lv
  ,ext_lines_chart_tab2_y_en
  ,ext_lines_chart_tab1_title_lv
  ,ext_lines_chart_tab1_title_en
  ,ext_lines_chart_tab2_title_lv
  ,ext_lines_chart_tab2_title_en
  )
VALUES (
  'h'
  ,'empl'
  ,'all'
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'''Visi'''
  ,'''All'''
  ,'''Strādā turpat'''
  ,'''Work locally'''
  ,'''Strādā citur'''
  ,'''Work elsewhere'''
  ,'''Skaits'''
  ,'''Number'''
  ,'''%'''
  ,'''%'''
  ,'''Latvijas iedzīvotāji visbiežāk strādā '',
LOWER(m_b_c.name_lv_loc),
'' – <b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> '',
CASE 
  WHEN get_pretty_number(''lv'', main.value_ind) LIKE ''% %''
    THEN ''nodarbināto''
  WHEN RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', main.value_ind), 2) NOT LIKE ''11''
    THEN ''nodarbinātais''
  ELSE ''nodarbinātie''
  END,
''. Tas veido <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot.value_ind),
''</b>% no <b>'',
get_pretty_number(''lv'', tot.value_ind),
''</b> Latvijas '',
CASE 
  WHEN get_pretty_number(''lv'', tot.value_ind) LIKE ''% %''
    THEN LOWER(m_v_c.name_lv_gen)
  WHEN RIGHT(get_pretty_number_num_part(''lv'', tot.value_ind), 1) LIKE ''1''
    AND RIGHT(get_pretty_number_num_part(''lv'', tot.value_ind), 2) NOT LIKE ''11''
    THEN ''nodarbinātā iedzīvotāja''
  ELSE LOWER(m_v_c.name_lv_dat)
  END,
''.'''
  ,'''Engaging <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> out of the <b>'',
get_pretty_number(''en'', tot.value_ind),
''</b> '',
LOWER(m_v_c.name_en),
'' of Latvia, businesses of the '',
LOWER(m_b_c.name_en),
'' employ the largest part of the Latvia residents – <b>'',
get_pretty_number(''en'', 100 * main.value_ind / tot.value_ind),
''</b>%.'''
  ,'''<b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> jeb <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot_empl.value_ind),
''</b>% no visiem Latvijas nodarbinātajiem iedzīvotājiem strādā savas dzīvesvietas teritorijā.'''
  ,'''The number of individuals who work in the territory of their residence totals <b>'',
get_pretty_number(''en'', main.value_ind),
''</b>, representing <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot_empl.value_ind),
''</b>% of all '',
LOWER(m_v_c.name_en),
'' of Latvia.'''
  ,'''<b>'',
get_pretty_number(''lv'', main.value_ind),
''</b> jeb <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot_empl.value_ind),
''</b>% no visiem Latvijas nodarbinātajiem iedzīvotājiem strādā ārpus savas dzīvesvietas teritorijas.'''
  ,'''Out of all '',
LOWER(m_v_c.name_en),
'' of Latvia, <b>'',
get_pretty_number(''en'', main.value_ind),
''</b> work outside their territory of residence, representing <b>'',
get_pretty_number(''lv'', 100 * main.value_ind / tot_empl.value_ind),
''</b>%.'''
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'''Iedzīvotāji darbaspējas vecumā (15–64 gadi)'''
  ,'''Working-age population (aged 15–64)'''
  ,'''No tiem nodarbināti'''
  ,'''Of these employed'''
  ,'''Nodarbinātības līmenis'''
  ,'''Employment rate'''
  ,'''Visi'''
  ,'''All'''
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'''Nodarbinātības līmenis'''
  ,'''Employment rate'''
  ,'''Gads'''
  ,'''Year'''
  ,'m_v_c.name_lv'
  ,'m_v_c.name_en'
  ,'''Gads'''
  ,'''Year'''
  ,'''Nodarbinātības līmenis'''
  ,'''Employment rate'''
  ,'m_v_c.name_lv_gen,
'' skaits'''
  ,'''Number of '',
LOWER(m_v_c.name_en)'
  ,'''Nodarbinātības līmenis, %'''
  ,'''Employment rate, %'''
  );