DROP TABLE IF EXISTS tea.texts_title_ext_home;

CREATE TABLE IF NOT EXISTS tea.texts_title_ext_home (
  r_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  ,home_work TEXT
  ,territory_type SMALLINT
  ,selected_territ TEXT
  ,ext_map_territory_info_home_title_lv TEXT
  ,ext_map_territory_info_home_title_en TEXT
  ,ext_map_territory_info_home_txt1_lv TEXT
  ,ext_map_territory_info_home_txt1_en TEXT
  ,ext_map_territory_info_home_txt2_lv TEXT
  ,ext_map_territory_info_home_txt2_en TEXT
  ,ext_map_territory_info_home_txt3_lv TEXT
  ,ext_map_territory_info_home_txt3_en TEXT
  );

ALTER TABLE tea.texts_title_ext_home OWNER TO tea_dev;

GRANT SELECT
  ON TABLE tea.texts_title_ext_home
  TO vdvv_web
    ,editor_texts
    ,admin_texts;

GRANT UPDATE
  ON TABLE tea.texts_title_ext_home
  TO editor_texts
    ,admin_texts;

GRANT DELETE
  ,INSERT
  ON TABLE tea.texts_title_ext_home
  TO admin_texts;

INSERT INTO tea.texts_title_ext_home (
  home_work
  ,territory_type
  ,selected_territ
  ,ext_map_territory_info_home_title_lv
  ,ext_map_territory_info_home_title_en
  ,ext_map_territory_info_home_txt1_lv
  ,ext_map_territory_info_home_txt1_en
  ,ext_map_territory_info_home_txt2_lv
  ,ext_map_territory_info_home_txt2_en
  ,ext_map_territory_info_home_txt3_lv
  ,ext_map_territory_info_home_txt3_en
  )
VALUES (
  'h'
  ,7
  ,'selected'
  ,'''Blīvi apdzīvotas teritorijas'''
  ,'''Densely populated areas'''
  ,
  'CASE
  WHEN dc.includes_lv IS NOT NULL AND dc.excludes_lv IS NOT NULL
    THEN CONCAT(''<b>'',
      t.name_lv,
      '' kā blīvi apdzīvota teritorija</b> ietver '',
      CASE 
        WHEN dc.includes_lv LIKE ''%,%''
          THEN ''vairākas pilsētai tuvumā esošas apdzīvotas vietas: ''
        ELSE ''pilsētai tuvumā esošu apdzīvotu vietu ''
        END,
      dc.includes_lv,
      ''.<br>Savukārt kā '',
      CASE 
        WHEN dc.excludes_lv LIKE ''%,%''
          THEN ''atsevišķas blīvi apdzīvotas teritorijas''
        ELSE ''atsevišķu blīvi apdzīvotu teritoriju''
        END,
      '' no '',
      t.name_lv_gen,
      '' pilsētas izdala '',
      dc.excludes_lv,
      ''.<br><br>'',
      t.name_lv_loc,
      '' kā blīvi apdzīvotā teritorijā ir <b>'',
      get_pretty_number(''lv'', empl_count),
      '' '',
      CASE 
        WHEN get_pretty_number(''lv'', empl_count) LIKE ''% %''
          THEN ''nodarbināto iedzīvotāju''
        WHEN RIGHT(get_pretty_number_num_part(''lv'', empl_count), 1) LIKE ''1''
          AND RIGHT(get_pretty_number_num_part(''lv'', empl_count), 2) NOT LIKE ''11''
          THEN ''nodarbinātais iedzīvotājs''
        ELSE ''nodarbinātie iedzīvotāji''
        END,
      ''</b>, kas ir par '',
      get_pretty_number(''lv'', ABS(empl_count_c_h.value_ind - empl_count)),
      '' '',
      CASE 
        WHEN empl_count_c_h.value_ind < empl_count
          THEN ''vairāk''
        ELSE ''mazāk''
        END,
      '' nekā '',
      t.name_lv_gen,
      '' pilsētā.'')
  WHEN dc.includes_lv IS NOT NULL AND dc.excludes_lv IS NULL
    THEN CONCAT(''<b>'',
      t.name_lv,
      '' kā blīvi apdzīvota teritorija</b> ietver '',
      CASE 
        WHEN dc.includes_lv LIKE ''%,%''
          THEN ''vairākas pilsētai tuvumā esošas apdzīvotas vietas: ''
        ELSE ''pilsētai tuvumā esošu apdzīvotu vietu ''
        END,
      dc.includes_lv,
      ''.<br><br>'',
      t.name_lv_loc,
      '' kā blīvi apdzīvotā teritorijā ir <b>'',
      get_pretty_number(''lv'', empl_count),
      '' '',
      CASE 
        WHEN get_pretty_number(''lv'', empl_count) LIKE ''% %''
          THEN ''nodarbināto iedzīvotāju''
        WHEN RIGHT(get_pretty_number_num_part(''lv'', empl_count), 1) LIKE ''1''
          AND RIGHT(get_pretty_number_num_part(''lv'', empl_count), 2) NOT LIKE ''11''
          THEN ''nodarbinātais iedzīvotājs''
        ELSE ''nodarbinātie iedzīvotāji''
        END,
      ''</b>, kas ir par '',
      get_pretty_number(''lv'', ABS(empl_count_c_h.value_ind - empl_count)),
      '' '',
      CASE 
        WHEN empl_count_c_h.value_ind < empl_count
          THEN ''vairāk''
        ELSE ''mazāk''
        END,
      '' nekā '',
      t.name_lv_gen,
      '' pilsētā.'')
  WHEN dc.includes_lv IS NULL AND dc.excludes_lv IS NOT NULL
    THEN CONCAT(''Kā '',
      CASE 
        WHEN dc.excludes_lv LIKE ''%,%''
          THEN ''atsevišķas blīvi apdzīvotas teritorijas''
        ELSE ''atsevišķu blīvi apdzīvotu teritoriju''
        END,
      '' no '',
      t.name_lv_gen,
      '' pilsētas izdala '',
      dc.excludes_lv,
      ''.<br><br>'',
      t.name_lv_loc,
      '' kā blīvi apdzīvotā teritorijā ir <b>'',
      get_pretty_number(''lv'', empl_count),
      '' '',
      CASE 
        WHEN get_pretty_number(''lv'', empl_count) LIKE ''% %''
          THEN ''nodarbināto iedzīvotāju''
        WHEN RIGHT(get_pretty_number_num_part(''lv'', empl_count), 1) LIKE ''1''
          AND RIGHT(get_pretty_number_num_part(''lv'', empl_count), 2) NOT LIKE ''11''
          THEN ''nodarbinātais iedzīvotājs''
        ELSE ''nodarbinātie iedzīvotāji''
        END,
      ''</b>, kas ir par '',
      get_pretty_number(''lv'', ABS(empl_count_c_h.value_ind - empl_count)),
      '' '',
      CASE 
        WHEN empl_count_c_h.value_ind < empl_count
          THEN ''vairāk''
        ELSE ''mazāk''
        END,
      '' nekā '',
      t.name_lv_gen,
      '' pilsētā.'')
  ELSE ''Nodarbināto skaits''
END'
  ,
  'CASE
  WHEN dc.includes_en IS NOT NULL AND dc.excludes_en IS NOT NULL
    THEN CONCAT(''<b>'',
      t.name_en,
      '' as densely populated area</b> includes '',
      CASE 
        WHEN dc.includes_en LIKE ''%,%''
          THEN ''many''
        ELSE dc.includes_en
        END,
      '' populated '',
      CASE 
        WHEN dc.includes_en LIKE ''%,%''
          THEN ''places''
        ELSE ''place''
        END,
      '' near the '',
      CASE 
        WHEN t.name_lv IN (''Rīga'', ''Daugavpils'', ''Jelgava'', ''Jēkabpils'', ''Jūrmala'', ''Liepāja'', ''Ogre'', ''Rēzekne'', ''Valmiera'')
          THEN ''city''
        ELSE ''town''
        END,
      CASE 
        WHEN dc.includes_en LIKE ''%,%''
          THEN '': ''
        ELSE NULL
        END,
      CASE 
        WHEN dc.includes_en LIKE ''%,%''
          THEN dc.includes_en
        ELSE NULL
        END,
      ''.<br>As separate densely populated '',
      CASE 
        WHEN dc.excludes_en LIKE ''%,%''
          THEN ''areas''
        ELSE ''area''
        END,
      '' from '',
      t.name_en,
      '' '',
      CASE 
        WHEN dc.excludes_en LIKE ''%,%''
          THEN ''have''
        ELSE ''has''
        END,
      '' been excluded '',
      dc.excludes_en,
      ''.<br><br>In '',
      t.name_en,
      '' as densely populated area, <b>'',
      get_pretty_number(''en'', empl_count),
      '' employees</b> are living which is '',
      get_pretty_number(''en'', ABS(empl_count_c_h.value_ind - empl_count)),
      '' '',
      CASE 
        WHEN empl_count_c_h.value_ind < empl_count
          THEN ''more''
        ELSE ''less''
        END,
      '' than in the '',
      t.name_en,
      '' '',
      CASE 
        WHEN t.name_lv IN (''Rīga'', ''Daugavpils'', ''Jelgava'', ''Jēkabpils'', ''Jūrmala'', ''Liepāja'', ''Ogre'', ''Rēzekne'', ''Valmiera'')
          THEN ''city''
        ELSE ''town''
        END,
      ''.'')
  WHEN dc.includes_en IS NOT NULL AND dc.excludes_en IS NULL
    THEN CONCAT(''<b>'',
      t.name_en,
      '' as densely populated area</b> includes '',
      CASE 
        WHEN dc.includes_en LIKE ''%,%''
          THEN ''many''
        ELSE dc.includes_en
        END,
      '' populated '',
      CASE 
        WHEN dc.includes_en LIKE ''%,%''
          THEN ''places''
        ELSE ''place''
        END,
      '' near the '',
      CASE 
        WHEN t.name_lv IN (''Rīga'', ''Daugavpils'', ''Jelgava'', ''Jēkabpils'', ''Jūrmala'', ''Liepāja'', ''Ogre'', ''Rēzekne'', ''Valmiera'')
          THEN ''city''
        ELSE ''town''
        END,
      CASE 
        WHEN dc.includes_en LIKE ''%,%''
          THEN '': ''
        ELSE NULL
        END,
      CASE 
        WHEN dc.includes_en LIKE ''%,%''
          THEN dc.includes_en
        ELSE NULL
        END,
      ''.<br><br>In '',
      t.name_en,
      '' as densely populated area, <b>'',
      get_pretty_number(''en'', empl_count),
      '' employees</b> are living which is '',
      get_pretty_number(''en'', ABS(empl_count_c_h.value_ind - empl_count)),
      '' '',
      CASE 
        WHEN empl_count_c_h.value_ind < empl_count
          THEN ''more''
        ELSE ''less''
        END,
      '' than in the '',
      t.name_en,
      '' '',
      CASE 
        WHEN t.name_lv IN (''Rīga'', ''Daugavpils'', ''Jelgava'', ''Jēkabpils'', ''Jūrmala'', ''Liepāja'', ''Ogre'', ''Rēzekne'', ''Valmiera'')
          THEN ''city''
        ELSE ''town''
        END,
      ''.'')
  WHEN dc.includes_en IS NULL AND dc.excludes_en IS NOT NULL
    THEN CONCAT(''As separate densely populated '',
      CASE 
        WHEN dc.excludes_en LIKE ''%,%''
          THEN ''areas''
        ELSE ''area''
        END,
      '' from '',
      t.name_en,
      '' '',
      CASE 
        WHEN dc.excludes_en LIKE ''%,%''
          THEN ''have''
        ELSE ''has''
        END,
      '' been excluded '',
      dc.excludes_en,
      ''.<br><br>In '',
      t.name_en,
      '' as densely populated area, <b>'',
      get_pretty_number(''en'', empl_count),
      '' employees</b> are living which is '',
      get_pretty_number(''en'', ABS(empl_count_c_h.value_ind - empl_count)),
      '' '',
      CASE 
        WHEN empl_count_c_h.value_ind < empl_count
          THEN ''more''
        ELSE ''less''
        END,
      '' than in the '',
      t.name_en,
      '' '',
      CASE 
        WHEN t.name_lv IN (''Rīga'', ''Daugavpils'', ''Jelgava'', ''Jēkabpils'', ''Jūrmala'', ''Liepāja'', ''Ogre'', ''Rēzekne'', ''Valmiera'')
          THEN ''city''
        ELSE ''town''
        END,
      ''.'')
  ELSE ''Number of employees''
END'
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title_ext_home (
  home_work
  ,territory_type
  ,selected_territ
  ,ext_map_territory_info_home_title_lv
  ,ext_map_territory_info_home_title_en
  ,ext_map_territory_info_home_txt1_lv
  ,ext_map_territory_info_home_txt1_en
  ,ext_map_territory_info_home_txt2_lv
  ,ext_map_territory_info_home_txt2_en
  ,ext_map_territory_info_home_txt3_lv
  ,ext_map_territory_info_home_txt3_en
  )
VALUES (
  'h'
  ,7
  ,'all'
  ,'''Blīvi apdzīvotas teritorijas'''
  ,'''Densely populated areas'''
  ,'''Blīvi apdzīvotā teritorijā (BAT) ēkās, kas neatrodas tālāk par 200 m viena no otras, ir vismaz 50 pastāvīgie iedzīvotāji vai darbvietas.<br><br>BAT nav administratīvi noteikta teritorija. To nosaka ar ģeotelpiskās statistikas metodēm.'''
  ,'''In densely populated areas (DPA), at least 50 people are living or working in buildings that are located no more than 200 meters from each other.<br><br>DPA is not set by administrative means. It is determined by methods of geospatial statistics.'''
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title_ext_home (
  home_work
  ,territory_type
  ,selected_territ
  ,ext_map_territory_info_home_title_lv
  ,ext_map_territory_info_home_title_en
  ,ext_map_territory_info_home_txt1_lv
  ,ext_map_territory_info_home_txt1_en
  ,ext_map_territory_info_home_txt2_lv
  ,ext_map_territory_info_home_txt2_en
  ,ext_map_territory_info_home_txt3_lv
  ,ext_map_territory_info_home_txt3_en
  )
VALUES (
  'w'
  ,7
  ,'all'
  ,'''Blīvi apdzīvotas teritorijas'''
  ,'''Densely populated areas'''
  ,'''Blīvi apdzīvotā teritorijā (BAT) ēkās, kas neatrodas tālāk par 200 m viena no otras, ir vismaz 50 pastāvīgie iedzīvotāji vai darbvietas.<br><br>BAT nav administratīvi noteikta teritorija. To nosaka ar ģeotelpiskās statistikas metodēm.'''
  ,'''In densely populated areas (DPA), at least 50 people are living or working in buildings that are located no more than 200 meters from each other.<br><br>DPA is not set by administrative means. It is determined by methods of geospatial statistics.'''
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title_ext_home (
  home_work
  ,territory_type
  ,selected_territ
  ,ext_map_territory_info_home_title_lv
  ,ext_map_territory_info_home_title_en
  ,ext_map_territory_info_home_txt1_lv
  ,ext_map_territory_info_home_txt1_en
  ,ext_map_territory_info_home_txt2_lv
  ,ext_map_territory_info_home_txt2_en
  ,ext_map_territory_info_home_txt3_lv
  ,ext_map_territory_info_home_txt3_en
  )
VALUES (
  'h'
  ,3
  ,'selected'
  ,'''Pašvaldības'''
  ,'''Municipalities'''
  ,'''Nodarbināto skaits'''
  ,'''Number of employed'''
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title_ext_home (
  home_work
  ,territory_type
  ,selected_territ
  ,ext_map_territory_info_home_title_lv
  ,ext_map_territory_info_home_title_en
  ,ext_map_territory_info_home_txt1_lv
  ,ext_map_territory_info_home_txt1_en
  ,ext_map_territory_info_home_txt2_lv
  ,ext_map_territory_info_home_txt2_en
  ,ext_map_territory_info_home_txt3_lv
  ,ext_map_territory_info_home_txt3_en
  )
VALUES (
  'w'
  ,3
  ,'selected'
  ,'''Pašvaldības'''
  ,'''Municipalities'''
  ,'''Darbvietu skaits'''
  ,'''Number of jobs'''
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title_ext_home (
  home_work
  ,territory_type
  ,selected_territ
  ,ext_map_territory_info_home_title_lv
  ,ext_map_territory_info_home_title_en
  ,ext_map_territory_info_home_txt1_lv
  ,ext_map_territory_info_home_txt1_en
  ,ext_map_territory_info_home_txt2_lv
  ,ext_map_territory_info_home_txt2_en
  ,ext_map_territory_info_home_txt3_lv
  ,ext_map_territory_info_home_txt3_en
  )
VALUES (
  'h'
  ,4
  ,'selected'
  ,'''Pagasti un pilsētas'''
  ,'''Cities, towns and rural territories'''
  ,'''Nodarbināto skaits'''
  ,'''Number of employed'''
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title_ext_home (
  home_work
  ,territory_type
  ,selected_territ
  ,ext_map_territory_info_home_title_lv
  ,ext_map_territory_info_home_title_en
  ,ext_map_territory_info_home_txt1_lv
  ,ext_map_territory_info_home_txt1_en
  ,ext_map_territory_info_home_txt2_lv
  ,ext_map_territory_info_home_txt2_en
  ,ext_map_territory_info_home_txt3_lv
  ,ext_map_territory_info_home_txt3_en
  )
VALUES (
  'w'
  ,4
  ,'selected'
  ,'''Pagasti un pilsētas'''
  ,'''Cities, towns and rural territories'''
  ,'''Darbvietu skaits'''
  ,'''Number of jobs'''
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  );

INSERT INTO tea.texts_title_ext_home (
  home_work
  ,territory_type
  ,selected_territ
  ,ext_map_territory_info_home_title_lv
  ,ext_map_territory_info_home_title_en
  ,ext_map_territory_info_home_txt1_lv
  ,ext_map_territory_info_home_txt1_en
  ,ext_map_territory_info_home_txt2_lv
  ,ext_map_territory_info_home_txt2_en
  ,ext_map_territory_info_home_txt3_lv
  ,ext_map_territory_info_home_txt3_en
  )
VALUES (
  'h'
  ,3
  ,'all'
  ,'''Pašvaldības'''
  ,'''Municipalities'''
  ,'''Pašvaldību skaits'''
  ,'''Number of municipalities'''
  ,'''No tām'''
  ,'''Of these'''
  ,'''un'''
  ,'''and'''
  );

INSERT INTO tea.texts_title_ext_home (
  home_work
  ,territory_type
  ,selected_territ
  ,ext_map_territory_info_home_title_lv
  ,ext_map_territory_info_home_title_en
  ,ext_map_territory_info_home_txt1_lv
  ,ext_map_territory_info_home_txt1_en
  ,ext_map_territory_info_home_txt2_lv
  ,ext_map_territory_info_home_txt2_en
  ,ext_map_territory_info_home_txt3_lv
  ,ext_map_territory_info_home_txt3_en
  )
VALUES (
  'w'
  ,3
  ,'all'
  ,'''Pašvaldības'''
  ,'''Municipalities'''
  ,'''Pašvaldību skaits'''
  ,'''Number of municipalities'''
  ,'''No tām'''
  ,'''Of these'''
  ,'''un'''
  ,'''and'''
  );

INSERT INTO tea.texts_title_ext_home (
  home_work
  ,territory_type
  ,selected_territ
  ,ext_map_territory_info_home_title_lv
  ,ext_map_territory_info_home_title_en
  ,ext_map_territory_info_home_txt1_lv
  ,ext_map_territory_info_home_txt1_en
  ,ext_map_territory_info_home_txt2_lv
  ,ext_map_territory_info_home_txt2_en
  ,ext_map_territory_info_home_txt3_lv
  ,ext_map_territory_info_home_txt3_en
  )
VALUES (
  'h'
  ,4
  ,'all'
  ,'''Pagasti un pilsētas'''
  ,'''Cities, towns and rural territories'''
  ,'''Teritoriālo vienību skaits'''
  ,'''Number of municipalities'''
  ,'''No tām'''
  ,'''Of these'''
  ,'''un'''
  ,'''and'''
  );

INSERT INTO tea.texts_title_ext_home (
  home_work
  ,territory_type
  ,selected_territ
  ,ext_map_territory_info_home_title_lv
  ,ext_map_territory_info_home_title_en
  ,ext_map_territory_info_home_txt1_lv
  ,ext_map_territory_info_home_txt1_en
  ,ext_map_territory_info_home_txt2_lv
  ,ext_map_territory_info_home_txt2_en
  ,ext_map_territory_info_home_txt3_lv
  ,ext_map_territory_info_home_txt3_en
  )
VALUES (
  'w'
  ,4
  ,'all'
  ,'''Pagasti un pilsētas'''
  ,'''Cities, towns and rural territories'''
  ,'''Teritoriālo vienību skaits'''
  ,'''Number of municipalities'''
  ,'''No tām'''
  ,'''Of these'''
  ,'''un'''
  ,'''and'''
  );

INSERT INTO tea.texts_title_ext_home (
  home_work
  ,territory_type
  ,selected_territ
  ,ext_map_territory_info_home_title_lv
  ,ext_map_territory_info_home_title_en
  ,ext_map_territory_info_home_txt1_lv
  ,ext_map_territory_info_home_txt1_en
  ,ext_map_territory_info_home_txt2_lv
  ,ext_map_territory_info_home_txt2_en
  ,ext_map_territory_info_home_txt3_lv
  ,ext_map_territory_info_home_txt3_en
  )
VALUES (
  'w'
  ,7
  ,'selected'
  ,'''Blīvi apdzīvotas teritorijas'''
  ,'''Densely populated areas'''
  ,
  'CASE
  WHEN dc.includes_lv IS NOT NULL AND dc.excludes_lv IS NOT NULL
    THEN CONCAT(''<b>'',
      t.name_lv,
      '' kā blīvi apdzīvota teritorija</b> ietver '',
      CASE 
        WHEN dc.includes_lv LIKE ''%,%''
          THEN ''vairākas pilsētai tuvumā esošas apdzīvotas vietas: ''
        ELSE ''pilsētai tuvumā esošu apdzīvotu vietu ''
        END,
      dc.includes_lv,
      ''.<br>Savukārt kā '',
      CASE 
        WHEN dc.excludes_lv LIKE ''%,%''
          THEN ''atsevišķas blīvi apdzīvotas teritorijas''
        ELSE ''atsevišķu blīvi apdzīvotu teritoriju''
        END,
      '' no '',
      t.name_lv_gen,
      '' pilsētas izdala '',
      dc.excludes_lv,
      ''.<br><br>'',
      t.name_lv_loc,
      '' kā blīvi apdzīvotā teritorijā ir <b>'',
      get_pretty_number(''lv'', empl_count),
      '' '',
      CASE 
        WHEN get_pretty_number(''lv'', empl_count) LIKE ''% %''
          THEN ''darbvietu''
        WHEN RIGHT(get_pretty_number_num_part(''lv'', empl_count), 1) LIKE ''1''
          AND RIGHT(get_pretty_number_num_part(''lv'', empl_count), 2) NOT LIKE ''11''
          THEN ''darbvieta''
        ELSE ''darbvietas''
        END,
      ''</b>, kas ir par '',
      get_pretty_number(''lv'', ABS(empl_count_c_w.value_ind - empl_count)),
      '' '',
      CASE 
        WHEN empl_count_c_w.value_ind < empl_count
          THEN ''vairāk''
        ELSE ''mazāk''
        END,
      '' nekā '',
      t.name_lv_gen,
      '' pilsētā.'')
  WHEN dc.includes_lv IS NOT NULL AND dc.excludes_lv IS NULL
    THEN CONCAT(''<b>'',
      t.name_lv,
      '' kā blīvi apdzīvota teritorija</b> ietver '',
      CASE 
        WHEN dc.includes_lv LIKE ''%,%''
          THEN ''vairākas pilsētai tuvumā esošas apdzīvotas vietas: ''
        ELSE ''pilsētai tuvumā esošu apdzīvotu vietu ''
        END,
      dc.includes_lv,
      ''.<br><br>'',
      t.name_lv_loc,
      '' kā blīvi apdzīvotā teritorijā ir <b>'',
      get_pretty_number(''lv'', empl_count),
      '' '',
      CASE 
        WHEN get_pretty_number(''lv'', empl_count) LIKE ''% %''
          THEN ''darbvietu''
        WHEN RIGHT(get_pretty_number_num_part(''lv'', empl_count), 1) LIKE ''1''
          AND RIGHT(get_pretty_number_num_part(''lv'', empl_count), 2) NOT LIKE ''11''
          THEN ''darbvieta''
        ELSE ''darbvietas''
        END,
      ''</b>, kas ir par '',
      get_pretty_number(''lv'', ABS(empl_count_c_w.value_ind - empl_count)),
      '' '',
      CASE 
        WHEN empl_count_c_w.value_ind < empl_count
          THEN ''vairāk''
        ELSE ''mazāk''
        END,
      '' nekā '',
      t.name_lv_gen,
      '' pilsētā.'')
  WHEN dc.includes_lv IS NULL AND dc.excludes_lv IS NOT NULL
    THEN CONCAT(''Kā '',
      CASE 
        WHEN dc.excludes_lv LIKE ''%,%''
          THEN ''atsevišķas blīvi apdzīvotas teritorijas''
        ELSE ''atsevišķu blīvi apdzīvotu teritoriju''
        END,
      '' no '',
      t.name_lv_gen,
      '' pilsētas izdala '',
      dc.excludes_lv,
      ''.<br><br>'',
      t.name_lv_loc,
      '' kā blīvi apdzīvotā teritorijā ir <b>'',
      get_pretty_number(''lv'', empl_count),
      '' '',
      CASE 
        WHEN get_pretty_number(''lv'', empl_count) LIKE ''% %''
          THEN ''darbvietu''
        WHEN RIGHT(get_pretty_number_num_part(''lv'', empl_count), 1) LIKE ''1''
          AND RIGHT(get_pretty_number_num_part(''lv'', empl_count), 2) NOT LIKE ''11''
          THEN ''darbvieta''
        ELSE ''darbvietas''
        END,
      ''</b>, kas ir par '',
      get_pretty_number(''lv'', ABS(empl_count_c_w.value_ind - empl_count)),
      '' '',
      CASE 
        WHEN empl_count_c_w.value_ind < empl_count
          THEN ''vairāk''
        ELSE ''mazāk''
        END,
      '' nekā '',
      t.name_lv_gen,
      '' pilsētā.'')
  ELSE ''Darbvietu skaits''
END'
  ,
  'CASE
  WHEN dc.includes_en IS NOT NULL AND dc.excludes_en IS NOT NULL
    THEN CONCAT(''<b>'',
      t.name_en,
      '' as densely populated area</b> includes '',
      CASE 
        WHEN dc.includes_en LIKE ''%,%''
          THEN ''many''
        ELSE dc.includes_en
        END,
      '' populated '',
      CASE 
        WHEN dc.includes_en LIKE ''%,%''
          THEN ''places''
        ELSE ''place''
        END,
      '' near the '',
      CASE 
        WHEN t.name_lv IN (''Rīga'', ''Daugavpils'', ''Jelgava'', ''Jēkabpils'', ''Jūrmala'', ''Liepāja'', ''Ogre'', ''Rēzekne'', ''Valmiera'')
          THEN ''city''
        ELSE ''town''
        END,
      CASE 
        WHEN dc.includes_en LIKE ''%,%''
          THEN '': ''
        ELSE NULL
        END,
      CASE 
        WHEN dc.includes_en LIKE ''%,%''
          THEN dc.includes_en
        ELSE NULL
        END,
      ''.<br>As separate densely populated '',
      CASE 
        WHEN dc.excludes_en LIKE ''%,%''
          THEN ''areas''
        ELSE ''area''
        END,
      '' from '',
      t.name_en,
      '' '',
      CASE 
        WHEN dc.excludes_en LIKE ''%,%''
          THEN ''have''
        ELSE ''has''
        END,
      '' been excluded '',
      dc.excludes_en,
      ''.<br><br>In '',
      t.name_en,
      '' as densely populated area, <b>'',
      get_pretty_number(''en'', empl_count),
      '' jobs</b> are located which is '',
      get_pretty_number(''en'', ABS(empl_count_c_w.value_ind - empl_count)),
      '' '',
      CASE 
        WHEN empl_count_c_w.value_ind < empl_count
          THEN ''more''
        ELSE ''less''
        END,
      '' than in the '',
      t.name_en,
      '' '',
      CASE 
        WHEN t.name_lv IN (''Rīga'', ''Daugavpils'', ''Jelgava'', ''Jēkabpils'', ''Jūrmala'', ''Liepāja'', ''Ogre'', ''Rēzekne'', ''Valmiera'')
          THEN ''city''
        ELSE ''town''
        END,
      ''.'')
  WHEN dc.includes_en IS NOT NULL AND dc.excludes_en IS NULL
    THEN CONCAT(''<b>'',
      t.name_en,
      '' as densely populated area</b> includes '',
      CASE 
        WHEN dc.includes_en LIKE ''%,%''
          THEN ''many''
        ELSE dc.includes_en
        END,
      '' populated '',
      CASE 
        WHEN dc.includes_en LIKE ''%,%''
          THEN ''places''
        ELSE ''place''
        END,
      '' near the '',
      CASE 
        WHEN t.name_lv IN (''Rīga'', ''Daugavpils'', ''Jelgava'', ''Jēkabpils'', ''Jūrmala'', ''Liepāja'', ''Ogre'', ''Rēzekne'', ''Valmiera'')
          THEN ''city''
        ELSE ''town''
        END,
      CASE 
        WHEN dc.includes_en LIKE ''%,%''
          THEN '': ''
        ELSE NULL
        END,
      CASE 
        WHEN dc.includes_en LIKE ''%,%''
          THEN dc.includes_en
        ELSE NULL
        END,
      ''.<br><br>In '',
      t.name_en,
      '' as densely populated area, <b>'',
      get_pretty_number(''en'', empl_count),
      '' jobs</b> are located which is '',
      get_pretty_number(''en'', ABS(empl_count_c_w.value_ind - empl_count)),
      '' '',
      CASE 
        WHEN empl_count_c_w.value_ind < empl_count
          THEN ''more''
        ELSE ''less''
        END,
      '' than in the '',
      t.name_en,
      '' '',
      CASE 
        WHEN t.name_lv IN (''Rīga'', ''Daugavpils'', ''Jelgava'', ''Jēkabpils'', ''Jūrmala'', ''Liepāja'', ''Ogre'', ''Rēzekne'', ''Valmiera'')
          THEN ''city''
        ELSE ''town''
        END,
      ''.'')
  WHEN dc.includes_en IS NULL AND dc.excludes_en IS NOT NULL
    THEN CONCAT(''As separate densely populated '',
      CASE 
        WHEN dc.excludes_en LIKE ''%,%''
          THEN ''areas''
        ELSE ''area''
        END,
      '' from '',
      t.name_en,
      '' '',
      CASE 
        WHEN dc.excludes_en LIKE ''%,%''
          THEN ''have''
        ELSE ''has''
        END,
      '' been excluded '',
      dc.excludes_en,
      ''.<br><br>In '',
      t.name_en,
      '' as densely populated area, <b>'',
      get_pretty_number(''en'', empl_count),
      '' jobs</b> are located which is '',
      get_pretty_number(''en'', ABS(empl_count_c_w.value_ind - empl_count)),
      '' '',
      CASE 
        WHEN empl_count_c_w.value_ind < empl_count
          THEN ''more''
        ELSE ''less''
        END,
      '' than in the '',
      t.name_en,
      '' '',
      CASE 
        WHEN t.name_lv IN (''Rīga'', ''Daugavpils'', ''Jelgava'', ''Jēkabpils'', ''Jūrmala'', ''Liepāja'', ''Ogre'', ''Rēzekne'', ''Valmiera'')
          THEN ''city''
        ELSE ''town''
        END,
      ''.'')
  ELSE ''Number of jobs''
END'
  ,NULL
  ,NULL
  ,NULL
  ,NULL
  );